services:
  website:
    build:
      context: .
    container_name: h2-website-dev
    environment:
      NODE_ENV: production
      PORT: "3100"
      HOST: "0.0.0.0"
    ports:
      - "3100:3100"
