services:
  website:
    build:
      context: .
    init: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - '127.0.0.1:3002:3002'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
