services:
  website:
    build:
      context: .
    container_name: h2-website
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOST: "0.0.0.0"
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
      GOOGLE_CHAT_WEBHOOK: ${GOOGLE_CHAT_WEBHOOK}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "3000:3000"
