name: Deploy to prod

on: 
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, nginx]
    steps:
      - name: Setup
        uses: actions/checkout@v2
      - name: Deploy
        run: docker compose up --build -d