name: Test Build

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    test_build:
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        steps:
            - name: Setup
              uses: actions/checkout@v2
            - name: Install PNPM
              run: npm install -g pnpm
            - name: Generate Prisma Client
              run: npx prisma generate
            - name: Install Dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
